<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract-module' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
   '{displayName} added tag {tagTitle} ' => '{displayName} がタグ {tagTitle} を追加しました',
    'Tag Added' => 'タグの追加',
    'Receive Notifications for New Taggings to your profile' => 'プロファイルへ新しいタグが追加されたときに通知を受け取ります'
];